/**
 * Illustrative demo data for the BRICS cooperation view.
 *
 * READ THIS BEFORE USING ANY NUMBER HERE.
 *
 * Every figure below is illustrative for demonstration.
 *
 * That honesty is enforced structurally: each record is typed with
 * `source: 'demo'` and the UI renders that label beside the data.
 */

import type { CountryCode, DataSource, RiskLevel } from '@shared/types.ts';

export interface RegionNode {
  id: string;
  countryCode: CountryCode;
  countryName: string;
  tier: 'core' | 'member' | 'partner';
  /** Recognisable agricultural region within the country. */
  region: string;
  flag: string;
  /** Percentage coordinates on the simplified map, not real projection. */
  map: { x: number; y: number };
  primaryCrop: string;
  secondaryCrops: string[];
  soilType: string;
  soilCondition: 'poor' | 'fair' | 'good';
  /** Millimetres in the last 30 days. */
  rainfall30dMm: number;
  averageTempC: number;
  /** Direction of yield versus the previous season. */
  yieldTrend: 'rising' | 'stable' | 'falling';
  yieldChangePct: number;
  diseaseRisk: RiskLevel;
  /** 0-100 composite of practices adopted. Invented. */
  sustainabilityScore: number;
  /** A regenerative practice this region is known for, for cross-border learning. */
  sharedPractice: string;
  source: DataSource;
}

/** Always 'demo'. Kept as a constant so no record can quietly claim otherwise. */
const SOURCE: DataSource = 'demo';

export const BRICS_REGIONS: RegionNode[] = [
  // ─── 1. Original / Core Founding 5 ──────────────────────────────────────────
  {
    id: 'in-maharashtra',
    countryCode: 'IN',
    countryName: 'India',
    tier: 'core',
    region: 'Maharashtra — Deccan Plateau',
    flag: '🇮🇳',
    map: { x: 68.5, y: 56 },
    primaryCrop: 'Cotton',
    secondaryCrops: ['Sorghum', 'Chickpea'],
    soilType: 'Black (regur)',
    soilCondition: 'fair',
    rainfall30dMm: 214,
    averageTempC: 27,
    yieldTrend: 'stable',
    yieldChangePct: 1.4,
    diseaseRisk: 'high',
    sustainabilityScore: 64,
    sharedPractice: 'Cotton–pulse intercropping to break pest cycles and fix nitrogen naturally',
    source: SOURCE,
  },
  {
    id: 'br-mato-grosso',
    countryCode: 'BR',
    countryName: 'Brazil',
    tier: 'core',
    region: 'Mato Grosso — Cerrado',
    flag: '🇧🇷',
    map: { x: 31, y: 63 },
    primaryCrop: 'Soybean',
    secondaryCrops: ['Maize', 'Cotton'],
    soilType: 'Oxisol (deep, acidic)',
    soilCondition: 'good',
    rainfall30dMm: 168,
    averageTempC: 26,
    yieldTrend: 'rising',
    yieldChangePct: 4.8,
    diseaseRisk: 'elevated',
    sustainabilityScore: 71,
    sharedPractice: 'No-till with permanent residue cover to hold soil carbon and deep moisture',
    source: SOURCE,
  },
  {
    id: 'za-free-state',
    countryCode: 'ZA',
    countryName: 'South Africa',
    tier: 'core',
    region: 'Free State — Maize Belt',
    flag: '🇿🇦',
    map: { x: 53.5, y: 76 },
    primaryCrop: 'Maize',
    secondaryCrops: ['Sunflower', 'Dry beans'],
    soilType: 'Sandy loam',
    soilCondition: 'fair',
    rainfall30dMm: 47,
    averageTempC: 19,
    yieldTrend: 'falling',
    yieldChangePct: -6.2,
    diseaseRisk: 'low',
    sustainabilityScore: 58,
    sharedPractice: 'Conservation agriculture with drought-tolerant open-pollinated varieties',
    source: SOURCE,
  },
  {
    id: 'cn-henan',
    countryCode: 'CN',
    countryName: 'China',
    tier: 'core',
    region: 'Henan — North China Plain',
    flag: '🇨🇳',
    map: { x: 78.5, y: 44 },
    primaryCrop: 'Winter Wheat',
    secondaryCrops: ['Maize', 'Groundnut'],
    soilType: 'Alluvial',
    soilCondition: 'good',
    rainfall30dMm: 96,
    averageTempC: 22,
    yieldTrend: 'rising',
    yieldChangePct: 2.9,
    diseaseRisk: 'elevated',
    sustainabilityScore: 67,
    sharedPractice: 'Precision multi-spectral nutrient timing to reduce chemical fertiliser leaching',
    source: SOURCE,
  },
  {
    id: 'ru-krasnodar',
    countryCode: 'RU',
    countryName: 'Russia',
    tier: 'core',
    region: 'Krasnodar — Kuban',
    flag: '🇷🇺',
    map: { x: 61, y: 33 },
    primaryCrop: 'Winter Wheat',
    secondaryCrops: ['Sunflower', 'Sugar beet'],
    soilType: 'Chernozem (black earth)',
    soilCondition: 'good',
    rainfall30dMm: 62,
    averageTempC: 21,
    yieldTrend: 'stable',
    yieldChangePct: 0.6,
    diseaseRisk: 'low',
    sustainabilityScore: 62,
    sharedPractice: 'Long 6-year crop rotations with deep-rooted perennial taproots',
    source: SOURCE,
  },

  // ─── 2. New Full Members (BRICS+) ──────────────────────────────────────────
  {
    id: 'eg-nile-delta',
    countryCode: 'EG',
    countryName: 'Egypt',
    tier: 'member',
    region: 'Nile Delta — Kafr El-Sheikh',
    flag: '🇪🇬',
    map: { x: 58, y: 45 },
    primaryCrop: 'Long-Staple Cotton',
    secondaryCrops: ['Citrus', 'Rice', 'Wheat'],
    soilType: 'Heavy Fluvisol (alluvial clay)',
    soilCondition: 'fair',
    rainfall30dMm: 12,
    averageTempC: 29,
    yieldTrend: 'rising',
    yieldChangePct: 2.1,
    diseaseRisk: 'elevated',
    sustainabilityScore: 63,
    sharedPractice: 'Laser land leveling and sub-surface tile drainage to prevent salinity accumulation',
    source: SOURCE,
  },
  {
    id: 'et-oromia',
    countryCode: 'ET',
    countryName: 'Ethiopia',
    tier: 'member',
    region: 'Oromia — Highland Rift Valley',
    flag: '🇪🇹',
    map: { x: 60.5, y: 58 },
    primaryCrop: 'Teff',
    secondaryCrops: ['Arabica Coffee', 'Faba Bean'],
    soilType: 'Vertisol & Nitisol',
    soilCondition: 'good',
    rainfall30dMm: 185,
    averageTempC: 20,
    yieldTrend: 'rising',
    yieldChangePct: 3.8,
    diseaseRisk: 'elevated',
    sustainabilityScore: 74,
    sharedPractice: 'Shade-grown multi-strata coffee agroforestry with indigenous nitrogen-fixing leguminous trees',
    source: SOURCE,
  },
  {
    id: 'ir-isfahan',
    countryCode: 'IR',
    countryName: 'Iran',
    tier: 'member',
    region: 'Isfahan — Zayandeh Basin',
    flag: '🇮🇷',
    map: { x: 65, y: 44 },
    primaryCrop: 'Pistachio',
    secondaryCrops: ['Saffron', 'Pomegranate'],
    soilType: 'Aridisol (calcareous)',
    soilCondition: 'fair',
    rainfall30dMm: 8,
    averageTempC: 31,
    yieldTrend: 'stable',
    yieldChangePct: 0.9,
    diseaseRisk: 'low',
    sustainabilityScore: 69,
    sharedPractice: 'Gravity-fed subterranean qanat underground water conveyance to eliminate evaporative loss',
    source: SOURCE,
  },
  {
    id: 'sa-al-ahsa',
    countryCode: 'SA',
    countryName: 'Saudi Arabia',
    tier: 'member',
    region: 'Al-Ahsa — Eastern Oasis',
    flag: '🇸🇦',
    map: { x: 63, y: 48 },
    primaryCrop: 'Date Palm (Khalas)',
    secondaryCrops: ['Alfalfa', 'Greenhouse Tomato'],
    soilType: 'Torripsamment (sandy desert)',
    soilCondition: 'fair',
    rainfall30dMm: 4,
    averageTempC: 35,
    yieldTrend: 'rising',
    yieldChangePct: 1.7,
    diseaseRisk: 'low',
    sustainabilityScore: 60,
    sharedPractice: 'Closed-loop precision pulse drip irrigation with desalinated brackish water recovery',
    source: SOURCE,
  },
  {
    id: 'ae-al-ain',
    countryCode: 'AE',
    countryName: 'UAE',
    tier: 'member',
    region: 'Abu Dhabi — Al Ain Oasis',
    flag: '🇦🇪',
    map: { x: 64.5, y: 49 },
    primaryCrop: 'Protected CEA Greens',
    secondaryCrops: ['Salicornia', 'Date Palm'],
    soilType: 'Calcaric Arenosol',
    soilCondition: 'poor',
    rainfall30dMm: 2,
    averageTempC: 36,
    yieldTrend: 'rising',
    yieldChangePct: 5.4,
    diseaseRisk: 'low',
    sustainabilityScore: 78,
    sharedPractice: 'Salt-tolerant halophyte bio-saline agriculture and atmospheric water-harvesting greenhouses',
    source: SOURCE,
  },
  {
    id: 'id-java',
    countryCode: 'ID',
    countryName: 'Indonesia',
    tier: 'member',
    region: 'Central Java — Merapi Slopes',
    flag: '🇮🇩',
    map: { x: 82, y: 68 },
    primaryCrop: 'Paddy Rice',
    secondaryCrops: ['Cassava', 'Cocoa', 'Chili'],
    soilType: 'Andosol (rich volcanic ash)',
    soilCondition: 'good',
    rainfall30dMm: 245,
    averageTempC: 28,
    yieldTrend: 'rising',
    yieldChangePct: 3.2,
    diseaseRisk: 'high',
    sustainabilityScore: 72,
    sharedPractice: 'Rice-duck-fish integrated agro-ecosystem to naturally control stem borers and weeds',
    source: SOURCE,
  },

  // ─── 3. Partner Countries ──────────────────────────────────────────────────
  {
    id: 'vn-mekong',
    countryCode: 'VN',
    countryName: 'Vietnam',
    tier: 'partner',
    region: 'Mekong Delta — An Giang',
    flag: '🇻🇳',
    map: { x: 80, y: 58 },
    primaryCrop: 'ST25 Fragrant Rice',
    secondaryCrops: ['Shrimp', 'Dragon Fruit'],
    soilType: 'Gleysol & Acid Sulfate',
    soilCondition: 'good',
    rainfall30dMm: 210,
    averageTempC: 29,
    yieldTrend: 'rising',
    yieldChangePct: 3.6,
    diseaseRisk: 'elevated',
    sustainabilityScore: 75,
    sharedPractice: 'Alternate Wetting and Drying (AWD) irrigation cutting methane emissions by 40%',
    source: SOURCE,
  },
  {
    id: 'th-chao-phraya',
    countryCode: 'TH',
    countryName: 'Thailand',
    tier: 'partner',
    region: 'Chao Phraya Basin — Suphan Buri',
    flag: '🇹🇭',
    map: { x: 77.5, y: 56 },
    primaryCrop: 'Jasmine Rice (Hom Mali)',
    secondaryCrops: ['Sugarcane', 'Cassava'],
    soilType: 'Alluvial Marine Clay',
    soilCondition: 'good',
    rainfall30dMm: 175,
    averageTempC: 30,
    yieldTrend: 'rising',
    yieldChangePct: 2.4,
    diseaseRisk: 'elevated',
    sustainabilityScore: 68,
    sharedPractice: 'Bio-Circular-Green (BCG) model transforming rice straw into biochar and mushroom substrate',
    source: SOURCE,
  },
  {
    id: 'my-pahang',
    countryCode: 'MY',
    countryName: 'Malaysia',
    tier: 'partner',
    region: 'Pahang — Cameron Lowlands',
    flag: '🇲🇾',
    map: { x: 79, y: 63 },
    primaryCrop: 'Oil Palm (Sustainable RSPO)',
    secondaryCrops: ['Cocoa', 'Durian'],
    soilType: 'Ultisol (red-yellow podzolic)',
    soilCondition: 'good',
    rainfall30dMm: 220,
    averageTempC: 27,
    yieldTrend: 'stable',
    yieldChangePct: 1.1,
    diseaseRisk: 'elevated',
    sustainabilityScore: 70,
    sharedPractice: 'Legume cover cropping with Mucuna bracteata to stop soil erosion and enrich mycorrhizae',
    source: SOURCE,
  },
  {
    id: 'ng-kano',
    countryCode: 'NG',
    countryName: 'Nigeria',
    tier: 'partner',
    region: 'Kano — Northern Guinea Savannah',
    flag: '🇳🇬',
    map: { x: 48, y: 54 },
    primaryCrop: 'Sorghum',
    secondaryCrops: ['Cowpea', 'Millet', 'Groundnut'],
    soilType: 'Ferric Luvisol',
    soilCondition: 'fair',
    rainfall30dMm: 95,
    averageTempC: 32,
    yieldTrend: 'rising',
    yieldChangePct: 2.8,
    diseaseRisk: 'low',
    sustainabilityScore: 61,
    sharedPractice: 'Farmer-Managed Natural Regeneration (FMNR) of indigenous Faidherbia albida fertilizer trees',
    source: SOURCE,
  },
  {
    id: 'kz-kostanay',
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
    tier: 'partner',
    region: 'Kostanay — Northern Steppe',
    flag: '🇰🇿',
    map: { x: 67, y: 32 },
    primaryCrop: 'Spring Wheat (Durum)',
    secondaryCrops: ['Flax', 'Barley', 'Sunflower'],
    soilType: 'Southern Chernozem',
    soilCondition: 'good',
    rainfall30dMm: 38,
    averageTempC: 18,
    yieldTrend: 'stable',
    yieldChangePct: 0.8,
    diseaseRisk: 'low',
    sustainabilityScore: 66,
    sharedPractice: 'Zero-tillage with snow-trapping stubble retention to preserve critical winter moisture',
    source: SOURCE,
  },
  {
    id: 'by-polesie',
    countryCode: 'BY',
    countryName: 'Belarus',
    tier: 'partner',
    region: 'Brest — Polesie Lowlands',
    flag: '🇧🇾',
    map: { x: 56, y: 28 },
    primaryCrop: 'Flax & Potatoes',
    secondaryCrops: ['Rye', 'Rapeseed'],
    soilType: 'Podzolic Peat-Bog Soil',
    soilCondition: 'fair',
    rainfall30dMm: 68,
    averageTempC: 17,
    yieldTrend: 'stable',
    yieldChangePct: 0.4,
    diseaseRisk: 'low',
    sustainabilityScore: 64,
    sharedPractice: 'Peatland hydrological rewetting buffers to maintain regional water tables and carbon sink',
    source: SOURCE,
  },
  {
    id: 'bo-altiplano',
    countryCode: 'BO',
    countryName: 'Bolivia',
    tier: 'partner',
    region: 'Altiplano — Oruro / Potosí',
    flag: '🇧🇴',
    map: { x: 28, y: 69 },
    primaryCrop: 'Royal Quinoa',
    secondaryCrops: ['Native Potatoes', 'Llama Fodder'],
    soilType: 'Volcanic Sandy Loam (high salinity)',
    soilCondition: 'fair',
    rainfall30dMm: 22,
    averageTempC: 12,
    yieldTrend: 'rising',
    yieldChangePct: 3.1,
    diseaseRisk: 'low',
    sustainabilityScore: 73,
    sharedPractice: 'Ancient suka kollus (raised bed canals) providing thermal radiation protection against frost',
    source: SOURCE,
  },
  {
    id: 'cu-havana',
    countryCode: 'CU',
    countryName: 'Cuba',
    tier: 'partner',
    region: 'Havana — Organopónicos Green Belt',
    flag: '🇨🇺',
    map: { x: 25, y: 49 },
    primaryCrop: 'Urban Organic Vegetables',
    secondaryCrops: ['Cassava', 'Tropical Fruit'],
    soilType: 'Structured Humic Compost Substrate',
    soilCondition: 'good',
    rainfall30dMm: 110,
    averageTempC: 28,
    yieldTrend: 'rising',
    yieldChangePct: 4.2,
    diseaseRisk: 'low',
    sustainabilityScore: 82,
    sharedPractice: '100% synthetic-free agroecology using Trichoderma biopesticides and vermicompost tea',
    source: SOURCE,
  },
  {
    id: 'ug-victoria',
    countryCode: 'UG',
    countryName: 'Uganda',
    tier: 'partner',
    region: 'Buganda — Lake Victoria Basin',
    flag: '🇺🇬',
    map: { x: 57, y: 61 },
    primaryCrop: 'Matooke Highland Banana',
    secondaryCrops: ['Robusta Coffee', 'Sweet Potato'],
    soilType: 'Ferralsol (deep weathered red clay)',
    soilCondition: 'good',
    rainfall30dMm: 165,
    averageTempC: 24,
    yieldTrend: 'rising',
    yieldChangePct: 2.7,
    diseaseRisk: 'high',
    sustainabilityScore: 70,
    sharedPractice: 'Thick organic banana mulch layers conserving 95% of rain infiltration and boosting earthworms',
    source: SOURCE,
  },
  {
    id: 'uz-fergana',
    countryCode: 'UZ',
    countryName: 'Uzbekistan',
    tier: 'partner',
    region: 'Fergana Valley — Andijan',
    flag: '🇺🇿',
    map: { x: 69, y: 38 },
    primaryCrop: 'Upland Cotton',
    secondaryCrops: ['Sweet Melons', 'Grapes', 'Wheat'],
    soilType: 'Serozem (grey desert soil)',
    soilCondition: 'fair',
    rainfall30dMm: 18,
    averageTempC: 27,
    yieldTrend: 'rising',
    yieldChangePct: 3.5,
    diseaseRisk: 'low',
    sustainabilityScore: 65,
    sharedPractice: 'Solar-powered automated micro-drip fertigation with saline wash drains to save Aral waters',
    source: SOURCE,
  },
];

/** Network-level roll-up. */
export function networkSummary() {
  const count = BRICS_REGIONS.length;
  const avgSustainability = Math.round(
    BRICS_REGIONS.reduce((sum, node) => sum + node.sustainabilityScore, 0) / count,
  );
  const atRisk = BRICS_REGIONS.filter((node) => node.diseaseRisk !== 'low').length;
  const rising = BRICS_REGIONS.filter((node) => node.yieldTrend === 'rising').length;
  const crops = new Set(BRICS_REGIONS.flatMap((node) => [node.primaryCrop, ...node.secondaryCrops]));

  const coreCount = BRICS_REGIONS.filter((n) => n.tier === 'core').length;
  const memberCount = BRICS_REGIONS.filter((n) => n.tier === 'member').length;
  const partnerCount = BRICS_REGIONS.filter((n) => n.tier === 'partner').length;

  return {
    count,
    avgSustainability,
    atRisk,
    rising,
    cropCount: crops.size,
    coreCount,
    memberCount,
    partnerCount,
  };
}
