import { useState } from 'react';
import { Sprout, FlaskConical, AlertTriangle, Target, Loader2, RotateCcw, Info } from 'lucide-react';
import type { NutrientLevel, SoilType } from '@shared/types.ts';
import { Card, SectionHeading, DataLabel } from '../../components/ui/Card.tsx';
import { Button } from '../../components/ui/Button.tsx';
import { SOIL_TYPES } from '../../lib/reference.ts';
import { useSoil } from '../../hooks/useSoil.ts';
import { useAppStore } from '../../store/appStore.ts';

const LABEL = 'block text-sm font-medium text-forest-800';
const CONTROL =
  'mt-1.5 min-h-11 w-full rounded-xl border border-hairline bg-surface px-3 text-base text-ink focus:border-forest-400';

const NUTRIENT_OPTIONS: Array<{ value: NutrientLevel | ''; label: string }> = [
  { value: '', label: 'Not sure' },
  { value: 'low', label: 'Low' },
  { value: 'medium', label: 'Medium' },
  { value: 'high', label: 'High' },
];

/** Optional numeric field: empty string means "not entered", never zero. */
function numberOrUndefined(raw: string): number | undefined {
  if (raw.trim() === '') return undefined;
  const parsed = Number(raw);
  return Number.isFinite(parsed) ? parsed : undefined;
}

export function SoilPage() {
  const storedSoil = useAppStore((store) => store.soil);
  const { status, soil, assessment, provenance, error, analyse, reset } = useSoil();

  const [soilType, setSoilType] = useState<SoilType>(storedSoil?.soilType ?? 'unknown');
  const [ph, setPh] = useState(storedSoil?.ph ? String(storedSoil.ph.value) : '');
  const [nitrogen, setNitrogen] = useState<NutrientLevel | ''>(storedSoil?.nitrogen?.value ?? '');
  const [phosphorus, setPhosphorus] = useState<NutrientLevel | ''>(
    storedSoil?.phosphorus?.value ?? '',
  );
  const [potassium, setPotassium] = useState<NutrientLevel | ''>(storedSoil?.potassium?.value ?? '');
  const [moisture, setMoisture] = useState(
    storedSoil?.moisturePct ? String(storedSoil.moisturePct.value) : '',
  );
  const [organicCarbon, setOrganicCarbon] = useState(
    storedSoil?.organicCarbonPct ? String(storedSoil.organicCarbonPct.value) : '',
  );

  const hasAnyValue =
    ph !== '' ||
    nitrogen !== '' ||
    phosphorus !== '' ||
    potassium !== '' ||
    moisture !== '' ||
    organicCarbon !== '' ||
    soilType !== 'unknown';

  function onSubmit(event: React.FormEvent) {
    event.preventDefault();
    if (!hasAnyValue) return;
    void analyse({
      soilType,
      ...(numberOrUndefined(ph) !== undefined ? { ph: numberOrUndefined(ph) } : {}),
      ...(nitrogen ? { nitrogen } : {}),
      ...(phosphorus ? { phosphorus } : {}),
      ...(potassium ? { potassium } : {}),
      ...(numberOrUndefined(moisture) !== undefined
        ? { moisturePct: numberOrUndefined(moisture) }
        : {}),
      ...(numberOrUndefined(organicCarbon) !== undefined
        ? { organicCarbonPct: numberOrUndefined(organicCarbon) }
        : {}),
    });
  }

  return (
    <div className="max-w-3xl space-y-4">
      <SectionHeading
        as="h1"
        icon={Sprout}
        title="Soil intelligence"
        description="Turn soil readings into a decision about what is actually limiting your yield."
      />

      {status === 'done' && soil && assessment ? (
        <div className="space-y-4">
          {/* Deterministic headline first — this is calculated, not generated. */}
          <Card elevated className="overflow-hidden">
            <div className="border-b border-hairline p-6">
              <div className="flex items-start gap-3">
                <span className="mt-0.5 grid size-9 shrink-0 place-items-center rounded-xl bg-clay-100 text-clay-700">
                  <Target className="size-[18px]" aria-hidden="true" />
                </span>
                <div className="min-w-0">
                  <p className="text-sm font-medium tracking-wide text-forest-600 uppercase">
                    Main limitation
                  </p>
                  <h2 className="mt-1 text-2xl font-semibold text-forest-800">
                    {soil.limitingFactor}
                  </h2>
                  <p className="mt-2 text-sm text-ink-muted">{assessment.limitingReason}</p>
                </div>
              </div>

              <div className="mt-5 rounded-xl bg-surface-sunken p-4">
                <p className="text-sm font-semibold text-forest-700">
                  pH: {assessment.phBand}
                </p>
                <p className="mt-1 text-sm text-ink-muted">{assessment.phNote}</p>
              </div>

              <p className="mt-3 flex items-start gap-2 text-xs text-ink-subtle">
                <Info className="mt-0.5 size-3.5 shrink-0" aria-hidden="true" />
                Calculated directly from the values you entered, not generated by AI.
              </p>
            </div>

            <div className="p-6">
              <p className="text-ink">{soil.summary}</p>

              <h3 className="mt-6 text-sm font-semibold tracking-wide text-forest-700 uppercase">
                What to do
              </h3>
              <ol className="mt-3 space-y-2">
                {soil.recommendations.map((item, index) => (
                  <li key={item} className="flex gap-3 text-sm">
                    <span className="grid size-5 shrink-0 place-items-center rounded-full bg-forest-50 text-[11px] font-semibold text-forest-700">
                      {index + 1}
                    </span>
                    <span className="text-ink">{item}</span>
                  </li>
                ))}
              </ol>

              {soil.regenerativePractices.length > 0 && (
                <>
                  <h3 className="mt-6 flex items-center gap-2 text-sm font-semibold tracking-wide text-forest-700 uppercase">
                    <Sprout className="size-4" aria-hidden="true" />
                    Building this soil over seasons
                  </h3>
                  <ul className="mt-3 space-y-2">
                    {soil.regenerativePractices.map((item) => (
                      <li key={item} className="flex gap-2.5 text-sm text-ink-muted">
                        <span
                          className="mt-[7px] size-1.5 shrink-0 rounded-full bg-forest-300"
                          aria-hidden="true"
                        />
                        {item}
                      </li>
                    ))}
                  </ul>
                </>
              )}

              {soil.cautions.length > 0 && (
                <>
                  <h3 className="mt-6 flex items-center gap-2 text-sm font-semibold tracking-wide text-clay-700 uppercase">
                    <AlertTriangle className="size-4" aria-hidden="true" />
                    Avoid
                  </h3>
                  <ul className="mt-3 space-y-2">
                    {soil.cautions.map((item) => (
                      <li key={item} className="flex gap-2.5 text-sm text-clay-700">
                        <span
                          className="mt-[7px] size-1.5 shrink-0 rounded-full bg-clay-300"
                          aria-hidden="true"
                        />
                        {item}
                      </li>
                    ))}
                  </ul>
                </>
              )}
            </div>

            <div className="border-t border-hairline px-6 py-4">
              <p className="text-xs text-ink-subtle">{soil.disclaimer}</p>
              {provenance && (
                <p className="mt-2 text-[11px] text-ink-subtle">
                  Advice by {provenance.model}
                  {provenance.cached ? ' · previously calculated' : ''}
                  {provenance.degraded ? ' · backup provider' : ''}
                </p>
              )}
            </div>
          </Card>

          <Button onClick={reset} variant="secondary">
            <RotateCcw className="size-4" aria-hidden="true" />
            Change the values
          </Button>
        </div>
      ) : (
        <form onSubmit={onSubmit} className="space-y-4">
          <Card className="p-5 sm:p-6">
            <div className="mb-5 flex items-center justify-between gap-3">
              <p className="flex items-center gap-2 text-sm font-medium text-forest-800">
                <FlaskConical className="size-4" aria-hidden="true" />
                Your soil readings
              </p>
              <DataLabel source="user" />
            </div>

            <div className="grid gap-5 sm:grid-cols-2">
              <div>
                <label htmlFor="soilType" className={LABEL}>
                  Soil type
                </label>
                <select
                  id="soilType"
                  value={soilType}
                  onChange={(event) => setSoilType(event.target.value as SoilType)}
                  className={CONTROL}
                >
                  {SOIL_TYPES.map(({ value, label }) => (
                    <option key={value} value={value}>
                      {label}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label htmlFor="ph" className={LABEL}>
                  pH <span className="font-normal text-ink-subtle">(3–10)</span>
                </label>
                <input
                  id="ph"
                  type="number"
                  inputMode="decimal"
                  step="0.1"
                  min="3"
                  max="10"
                  value={ph}
                  onChange={(event) => setPh(event.target.value)}
                  placeholder="e.g. 6.4"
                  className={CONTROL}
                />
              </div>

              {(
                [
                  ['nitrogen', 'Nitrogen', nitrogen, setNitrogen],
                  ['phosphorus', 'Phosphorus', phosphorus, setPhosphorus],
                  ['potassium', 'Potassium', potassium, setPotassium],
                ] as const
              ).map(([id, label, value, setter]) => (
                <div key={id}>
                  <label htmlFor={id} className={LABEL}>
                    {label}
                  </label>
                  <select
                    id={id}
                    value={value}
                    onChange={(event) => setter(event.target.value as NutrientLevel | '')}
                    className={CONTROL}
                  >
                    {NUTRIENT_OPTIONS.map((option) => (
                      <option key={option.value} value={option.value}>
                        {option.label}
                      </option>
                    ))}
                  </select>
                </div>
              ))}

              <div>
                <label htmlFor="moisture" className={LABEL}>
                  Moisture <span className="font-normal text-ink-subtle">(%)</span>
                </label>
                <input
                  id="moisture"
                  type="number"
                  inputMode="numeric"
                  min="0"
                  max="100"
                  value={moisture}
                  onChange={(event) => setMoisture(event.target.value)}
                  placeholder="e.g. 42"
                  className={CONTROL}
                />
              </div>

              <div>
                <label htmlFor="organicCarbon" className={LABEL}>
                  Organic carbon <span className="font-normal text-ink-subtle">(%)</span>
                </label>
                <input
                  id="organicCarbon"
                  type="number"
                  inputMode="decimal"
                  step="0.1"
                  min="0"
                  max="30"
                  value={organicCarbon}
                  onChange={(event) => setOrganicCarbon(event.target.value)}
                  placeholder="e.g. 0.6"
                  className={CONTROL}
                />
              </div>
            </div>

            <p className="mt-5 text-xs text-ink-subtle">
              Enter only what you know. Blank fields are left out of the advice rather than guessed —
              nothing here is estimated on your behalf.
            </p>
          </Card>

          {error && (
            <p role="alert" className="text-sm text-clay-700">
              {error}
            </p>
          )}

          <Button type="submit" size="lg" fullWidth disabled={!hasAnyValue || status === 'working'}>
            {status === 'working' ? (
              <>
                <Loader2 className="size-5 animate-spin" aria-hidden="true" />
                Reading your soil…
              </>
            ) : (
              <>
                <Sprout className="size-5" aria-hidden="true" />
                Analyse soil
              </>
            )}
          </Button>
        </form>
      )}
    </div>
  );
}
